# CMake generated Testfile for 
# Source directory: C:/Users/user/Desktop/Transfo_Model/Tests
# Build directory: C:/Users/user/Desktop/Transfo_Model/build_diag3
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[cpwl_adaa]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Debug/test_cpwl_adaa.exe")
  set_tests_properties([=[cpwl_adaa]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;76;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[cpwl_adaa]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Release/test_cpwl_adaa.exe")
  set_tests_properties([=[cpwl_adaa]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;76;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[cpwl_adaa]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/MinSizeRel/test_cpwl_adaa.exe")
  set_tests_properties([=[cpwl_adaa]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;76;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[cpwl_adaa]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/RelWithDebInfo/test_cpwl_adaa.exe")
  set_tests_properties([=[cpwl_adaa]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;76;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
else()
  add_test([=[cpwl_adaa]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[cpwl_passivity]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Debug/test_cpwl_passivity.exe")
  set_tests_properties([=[cpwl_passivity]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;77;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[cpwl_passivity]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Release/test_cpwl_passivity.exe")
  set_tests_properties([=[cpwl_passivity]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;77;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[cpwl_passivity]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/MinSizeRel/test_cpwl_passivity.exe")
  set_tests_properties([=[cpwl_passivity]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;77;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[cpwl_passivity]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/RelWithDebInfo/test_cpwl_passivity.exe")
  set_tests_properties([=[cpwl_passivity]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;77;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
else()
  add_test([=[cpwl_passivity]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[hsim_diagnostics]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Debug/test_hsim_diagnostics.exe")
  set_tests_properties([=[hsim_diagnostics]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;78;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[hsim_diagnostics]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Release/test_hsim_diagnostics.exe")
  set_tests_properties([=[hsim_diagnostics]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;78;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[hsim_diagnostics]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/MinSizeRel/test_hsim_diagnostics.exe")
  set_tests_properties([=[hsim_diagnostics]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;78;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[hsim_diagnostics]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/RelWithDebInfo/test_hsim_diagnostics.exe")
  set_tests_properties([=[hsim_diagnostics]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;78;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
else()
  add_test([=[hsim_diagnostics]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[plugin_integration]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Debug/test_plugin_integration.exe")
  set_tests_properties([=[plugin_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;79;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[plugin_integration]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Release/test_plugin_integration.exe")
  set_tests_properties([=[plugin_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;79;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[plugin_integration]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/MinSizeRel/test_plugin_integration.exe")
  set_tests_properties([=[plugin_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;79;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[plugin_integration]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/RelWithDebInfo/test_plugin_integration.exe")
  set_tests_properties([=[plugin_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;79;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
else()
  add_test([=[plugin_integration]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[dynamic_losses]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Debug/test_dynamic_losses.exe")
  set_tests_properties([=[dynamic_losses]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;80;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[dynamic_losses]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Release/test_dynamic_losses.exe")
  set_tests_properties([=[dynamic_losses]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;80;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[dynamic_losses]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/MinSizeRel/test_dynamic_losses.exe")
  set_tests_properties([=[dynamic_losses]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;80;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[dynamic_losses]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/RelWithDebInfo/test_dynamic_losses.exe")
  set_tests_properties([=[dynamic_losses]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;80;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
else()
  add_test([=[dynamic_losses]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[dynamic_parallel_adaptor]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Debug/test_dynamic_parallel_adaptor.exe")
  set_tests_properties([=[dynamic_parallel_adaptor]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;81;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[dynamic_parallel_adaptor]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Release/test_dynamic_parallel_adaptor.exe")
  set_tests_properties([=[dynamic_parallel_adaptor]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;81;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[dynamic_parallel_adaptor]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/MinSizeRel/test_dynamic_parallel_adaptor.exe")
  set_tests_properties([=[dynamic_parallel_adaptor]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;81;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[dynamic_parallel_adaptor]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/RelWithDebInfo/test_dynamic_parallel_adaptor.exe")
  set_tests_properties([=[dynamic_parallel_adaptor]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;81;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
else()
  add_test([=[dynamic_parallel_adaptor]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[lc_resonance]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Debug/test_lc_resonance.exe")
  set_tests_properties([=[lc_resonance]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;82;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[lc_resonance]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Release/test_lc_resonance.exe")
  set_tests_properties([=[lc_resonance]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;82;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[lc_resonance]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/MinSizeRel/test_lc_resonance.exe")
  set_tests_properties([=[lc_resonance]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;82;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[lc_resonance]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/RelWithDebInfo/test_lc_resonance.exe")
  set_tests_properties([=[lc_resonance]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;82;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
else()
  add_test([=[lc_resonance]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[nonlinear_lm]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Debug/test_nonlinear_lm.exe")
  set_tests_properties([=[nonlinear_lm]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;83;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[nonlinear_lm]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Release/test_nonlinear_lm.exe")
  set_tests_properties([=[nonlinear_lm]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;83;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[nonlinear_lm]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/MinSizeRel/test_nonlinear_lm.exe")
  set_tests_properties([=[nonlinear_lm]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;83;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[nonlinear_lm]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/RelWithDebInfo/test_nonlinear_lm.exe")
  set_tests_properties([=[nonlinear_lm]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;83;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
else()
  add_test([=[nonlinear_lm]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[circuit_model]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Debug/test_circuit_model.exe")
  set_tests_properties([=[circuit_model]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;84;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[circuit_model]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Release/test_circuit_model.exe")
  set_tests_properties([=[circuit_model]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;84;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[circuit_model]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/MinSizeRel/test_circuit_model.exe")
  set_tests_properties([=[circuit_model]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;84;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[circuit_model]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/RelWithDebInfo/test_circuit_model.exe")
  set_tests_properties([=[circuit_model]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;84;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
else()
  add_test([=[circuit_model]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[diode_leaf]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Debug/test_diode_leaf.exe")
  set_tests_properties([=[diode_leaf]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;85;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[diode_leaf]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Release/test_diode_leaf.exe")
  set_tests_properties([=[diode_leaf]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;85;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[diode_leaf]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/MinSizeRel/test_diode_leaf.exe")
  set_tests_properties([=[diode_leaf]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;85;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[diode_leaf]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/RelWithDebInfo/test_diode_leaf.exe")
  set_tests_properties([=[diode_leaf]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;85;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
else()
  add_test([=[diode_leaf]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[bjt_leaf]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Debug/test_bjt_leaf.exe")
  set_tests_properties([=[bjt_leaf]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;86;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[bjt_leaf]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Release/test_bjt_leaf.exe")
  set_tests_properties([=[bjt_leaf]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;86;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[bjt_leaf]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/MinSizeRel/test_bjt_leaf.exe")
  set_tests_properties([=[bjt_leaf]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;86;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[bjt_leaf]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/RelWithDebInfo/test_bjt_leaf.exe")
  set_tests_properties([=[bjt_leaf]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;86;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
else()
  add_test([=[bjt_leaf]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[input_stage]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Debug/test_input_stage.exe")
  set_tests_properties([=[input_stage]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;94;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[input_stage]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Release/test_input_stage.exe")
  set_tests_properties([=[input_stage]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;94;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[input_stage]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/MinSizeRel/test_input_stage.exe")
  set_tests_properties([=[input_stage]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;94;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[input_stage]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/RelWithDebInfo/test_input_stage.exe")
  set_tests_properties([=[input_stage]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;94;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
else()
  add_test([=[input_stage]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[neve_path]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Debug/test_neve_path.exe")
  set_tests_properties([=[neve_path]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;102;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[neve_path]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Release/test_neve_path.exe")
  set_tests_properties([=[neve_path]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;102;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[neve_path]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/MinSizeRel/test_neve_path.exe")
  set_tests_properties([=[neve_path]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;102;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[neve_path]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/RelWithDebInfo/test_neve_path.exe")
  set_tests_properties([=[neve_path]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;102;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
else()
  add_test([=[neve_path]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[je990_path]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Debug/test_je990_path.exe")
  set_tests_properties([=[je990_path]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;110;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[je990_path]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Release/test_je990_path.exe")
  set_tests_properties([=[je990_path]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;110;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[je990_path]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/MinSizeRel/test_je990_path.exe")
  set_tests_properties([=[je990_path]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;110;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[je990_path]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/RelWithDebInfo/test_je990_path.exe")
  set_tests_properties([=[je990_path]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;110;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
else()
  add_test([=[je990_path]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[output_stage]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Debug/test_output_stage.exe")
  set_tests_properties([=[output_stage]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;118;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[output_stage]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Release/test_output_stage.exe")
  set_tests_properties([=[output_stage]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;118;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[output_stage]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/MinSizeRel/test_output_stage.exe")
  set_tests_properties([=[output_stage]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;118;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[output_stage]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/RelWithDebInfo/test_output_stage.exe")
  set_tests_properties([=[output_stage]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;118;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
else()
  add_test([=[output_stage]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[preamp_full]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Debug/test_preamp_full.exe")
  set_tests_properties([=[preamp_full]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;126;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[preamp_full]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Release/test_preamp_full.exe")
  set_tests_properties([=[preamp_full]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;126;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[preamp_full]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/MinSizeRel/test_preamp_full.exe")
  set_tests_properties([=[preamp_full]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;126;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[preamp_full]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/RelWithDebInfo/test_preamp_full.exe")
  set_tests_properties([=[preamp_full]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;126;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
else()
  add_test([=[preamp_full]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[preamp_plugin]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Debug/test_preamp_plugin.exe")
  set_tests_properties([=[preamp_plugin]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;134;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[preamp_plugin]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Release/test_preamp_plugin.exe")
  set_tests_properties([=[preamp_plugin]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;134;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[preamp_plugin]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/MinSizeRel/test_preamp_plugin.exe")
  set_tests_properties([=[preamp_plugin]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;134;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[preamp_plugin]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/RelWithDebInfo/test_preamp_plugin.exe")
  set_tests_properties([=[preamp_plugin]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;134;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
else()
  add_test([=[preamp_plugin]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[preamp_audio_sweep]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Debug/test_preamp_audio_sweep.exe")
  set_tests_properties([=[preamp_audio_sweep]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;142;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[preamp_audio_sweep]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Release/test_preamp_audio_sweep.exe")
  set_tests_properties([=[preamp_audio_sweep]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;142;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[preamp_audio_sweep]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/MinSizeRel/test_preamp_audio_sweep.exe")
  set_tests_properties([=[preamp_audio_sweep]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;142;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[preamp_audio_sweep]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/RelWithDebInfo/test_preamp_audio_sweep.exe")
  set_tests_properties([=[preamp_audio_sweep]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;142;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
else()
  add_test([=[preamp_audio_sweep]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[preamp_diagnostic]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Debug/test_preamp_diagnostic.exe")
  set_tests_properties([=[preamp_diagnostic]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;150;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[preamp_diagnostic]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/Release/test_preamp_diagnostic.exe")
  set_tests_properties([=[preamp_diagnostic]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;150;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[preamp_diagnostic]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/MinSizeRel/test_preamp_diagnostic.exe")
  set_tests_properties([=[preamp_diagnostic]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;150;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[preamp_diagnostic]=] "C:/Users/user/Desktop/Transfo_Model/build_diag3/RelWithDebInfo/test_preamp_diagnostic.exe")
  set_tests_properties([=[preamp_diagnostic]=] PROPERTIES  _BACKTRACE_TRIPLES "C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;150;add_test;C:/Users/user/Desktop/Transfo_Model/Tests/CMakeLists.txt;0;")
else()
  add_test([=[preamp_diagnostic]=] NOT_AVAILABLE)
endif()
